### ISSUE TITLE
Gateway discovery goes in timeout

### ISSUE THREAD

**Issue by roccomuso** [bcoin-org/bupnp#2]
```javascript
const UPNP = require('./lib/upnp')
UPNP.RESPONSE_TIMEOUT = 10*1000

UPNP.discover().then(console.log).catch(console.error)
```

Output:
```
Error: Request timed out.
    at Timeout.timeout.setTimeout [as _onTimeout] (/home/user/Desktop/REPOS/bupnp/lib/upnp.js:89:22)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5)
```

I tried with [node-ssdp](https://github.com/diversario/node-ssdp) and it works.

```javascript
var Client = require('node-ssdp').Client
, client = new Client();

client.on('response', function (headers, statusCode, rinfo) {
   console.log('Got a response to an m-search.', headers, statusCode, rinfo);
});

// get a list of all services on the network
setInterval(()=>{
  client.search('ssdp:all');
}, 3000)
```
Output:
```
{ 'CACHE-CONTROL': 'max-age=3600',
  EXT: '',
  LOCATION: 'http://192.168.88.1:2828/gateway.xml',
  SERVER: 'RouterOS/6.35.2UPnP/1.0 MikroTik UPnP/1.0',
  ST: 'urn:schemas-upnp-org:device:InternetGatewayDevice:1',
  USN: 'uuid:UUID-MIKROTIK-INTERNET-GATEWAY-DEVICE-TZ62-R761::urn:schemas-upnp-org:device:InternetGatewayDevice:1' }

200

{ address: '192.168.88.1', family: 'IPv4', port: 1900, size: 323}
```

Why bupnp doesn't discover it?

**Comment by chjj** [comment]
Not sure. I would need access to a router that with UPnP support to test this again. Not sure I have one readily available at the moment.

All I know is that this module seemed to work in practice the last time I was on a network with a UPnP-capable router.
